temp: Revert "include stat.h"
(cherry picked from commit 83abfe26c)

This reverts temp: include stat.h.  Without it, cygwin/stat.h pulls in
machine/types.h, which defines struct flock a second time and breaks the
cygserver build:

  machine/types.h:35:8: error: redefinition of struct flock
  make: *** [Makefile:1062: cygserver-sysv_shm.o] Error 1